internet_shop/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
    path('cart_change/', views.cart_change, name='cart_change'),
]

internet_shop/internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from internet_shop.settings import DEBUG
from django.conf.urls.static import static
from internet_shop import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('catalog/', include('tovari.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('orders/', include('orders.urls', namespace='orders')),
] 

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internet_shop/shop/urls.py
from django.urls import path
from shop import views 

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'), 
    path('contacts/', views.contacts, name='contacts'),
]

internet_shop/tovari/urls.py
from django.urls import path
from tovari.views import (
    ProductListAPIView, 
    ProductDetailAPIView, 
    generate_pdf, 
    catalog, 
    product
)

app_name = 'tovari'

urlpatterns = [
    # API маршруты
    path('api/products/', ProductListAPIView.as_view(), name='product_list'),
    path('api/products/<int:pk>/', ProductDetailAPIView.as_view(), name='product_detail'),

    # Маршруты каталога и товаров
    path('catalog/<slug:category_slug>/', catalog, name='catalog'),
    path('product/<slug:product_slug>/', product, name='product'),

    # Маршрут для генерации PDF
    path('generate-pdf/<slug:product_slug>/', generate_pdf, name='generate_pdf'),

    # Поиск (если используется)
    path('search/', catalog, name='search'),
    path('<slug:category_slug>/', catalog, name='index'),
]

internet_shop/users/urls.py
from django.urls import path
from users.views import LoginView, RegistrationView, ProfileView, LogoutView, UsersCartView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cart/', UsersCartView.as_view(), name='users_cart'),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

internet_shop/tovari/models.py
from django.db import models
from datetime import datetime
from django.utils.text import slugify

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.TextField(max_length=500, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category' 
        verbose_name = 'Категорию'     
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name     


class Products(models.Model):
    name = models.CharField(max_length=150, unique=False, verbose_name='Название')
    slug = models.TextField(max_length=500, unique=False, blank=True, null=True, verbose_name='URL')
    discription = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='tovari_images', blank=True, null=True)
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Скидка в %')    
    quantity = models.PositiveBigIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey('Categories', on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('id',)



    def __str__(self):
        return f'{self.name} Количество - {self.quantity} {self.price}$' 
    
    def display_id(self):
        return f'№ {"_".join(f"_{self.id:05}_")}'

    
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount/100, 2)
       
        return self.price

internet_shop/tovari/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage
from tovari.models import Products, Categories
from tovari.utils import q_search
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.pagesizes import letter
import os
from django.conf import settings
from PIL import Image
from reportlab.lib.utils import ImageReader

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from tovari.serializers import ProductSerializer


def split_text(text, words_per_line=6):
    """Разделить текст на строки с заданным количеством слов."""
    words = text.split()
    lines = []
    for i in range(0, len(words), words_per_line):
        lines.append(" ".join(words[i:i + words_per_line]))
    return lines


def generate_pdf(request, product_slug):
    font_path = os.path.join(settings.BASE_DIR, 'shop/static/deps/fonts/DejaVuSans.ttf')
    pdfmetrics.registerFont(TTFont('DejaVuSans', font_path))

    product = get_object_or_404(Products, slug=product_slug)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{product.name}.pdf"'

    p = canvas.Canvas(response, pagesize=letter)

    p.setFont("DejaVuSans", 12)
    p.setFont("DejaVuSans", 16)
    p.drawString(100, 800, f"Информация о товаре: {product.name}")

    y = 750
    p.setFont("DejaVuSans", 12)
    p.drawString(50, y, f"ID: {product.id}")
    y -= 20
    p.drawString(50, y, f"Название: {product.name}")
    y -= 20
    p.drawString(50, y, f"Цена: {product.sell_price()} $")
    y -= 20
    p.drawString(50, y, f"Количество: {product.quantity}")
    y -= 20

    if product.discription:
        p.drawString(50, y, "Описание:")
        y -= 20
        description_lines = split_text(product.discription, words_per_line=6)
        for line in description_lines:
            p.drawString(50, y, line)
            y -= 20

    if product.image:
        try:
            image_path = product.image.path
            img = Image.open(image_path)
            img = img.resize((200, 200))
            image_reader = ImageReader(img)

            p.drawImage(image_reader, 50, y - 200, width=200, height=200)
        except Exception as e:
            p.drawString(50, y, f"Ошибка при загрузке изображения: {e}")

    p.save()
    return response


def catalog(request, category_slug=None):
    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    if query:
        tovari = q_search(query)
        if not tovari.exists():
            context = {
                'title': 'Результаты не найдены',
                'tovari': [],
                'query': query,
                'slug_url': category_slug,
            }
            return render(request, 'tovari/catalog.html', context)

    elif category_slug:
        if category_slug == 'vse-tovary':
            tovari = Products.objects.all()
        else:
            category = get_object_or_404(Categories, slug=category_slug)
            tovari = Products.objects.filter(category=category)
            if not tovari.exists():
                context = {
                    'title': f'Категория {category.name} пуста',
                    'tovari': [],
                    'slug_url': category_slug,
                }
                return render(request, 'tovari/catalog.html', context)
    else:
        tovari = Products.objects.all()

    if on_sale == 'on':
        tovari = tovari.filter(discount__gt=0, discount__lte=100)

    if order_by and order_by != "default":
        tovari = tovari.order_by(order_by)

    paginator = Paginator(tovari, 3)
    try:
        current_page = paginator.page(int(page))
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)

    context = {
        'title': f'Madi - {category_slug.capitalize() if category_slug else "Каталог"}',
        'tovari': current_page,
        'slug_url': category_slug,
        'query': query,
    }
    return render(request, 'tovari/catalog.html', context)


def product(request, product_slug):
    product = get_object_or_404(Products, slug=product_slug)

    context = {
        'product': product,
    }
    return render(request, 'tovari/product.html', context=context)

class ProductListAPIView(APIView):
    def get(self, request):
        """Получение списка всех товаров"""
        products = Products.objects.all()
        serializer = ProductSerializer(products, many=True)
        return Response(serializer.data)

    def post(self, request):
        """Добавление нового товара"""
        serializer = ProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ProductDetailAPIView(APIView):
    def get(self, request, pk):
        """Получение деталей конкретного товара"""
        product = get_object_or_404(Products, pk=pk)
        serializer = ProductSerializer(product)
        return Response(serializer.data)

    def put(self, request, pk):
        """Обновление товара"""
        product = get_object_or_404(Products, pk=pk)
        serializer = ProductSerializer(product, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        """Удаление товара"""
        product = get_object_or_404(Products, pk=pk)
        product.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

internet_shop/tovari/templates/tovari/catalog.html
{% extends "base.html" %}
{% load static %}
{% load tovari_tags %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock %}


{% block name %}

    <div class="row">
        <!-- Форма фильтров -->
        <div class="dropdown mb-2">
            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Фильтры
            </button>

            <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url 'catalog:index' slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                <!-- Фильтр по акциям -->
                <div class="form-check text-white mx-3">
                    <input 
                        class="form-check-input" 
                        type="checkbox" 
                        name="on_sale" 
                        id="flexCheckDefault" 
                        value="on" 
                        {% if request.GET.on_sale == 'on' %}checked{% endif %}>
                    {% if request.GET.q %}
                        <input type="hidden" name="q" value="{{request.GET.q}}">
                    {% endif %}
                    
                    <label class="form-check-label" for="flexCheckDefault">
                        Товары по акции
                    </label>
                </div>

                <!-- Сортировка -->
                <p class="text-white mx-3 mt-3">Сортировать:</p>
                <div class="form-check text-white mx-3">
                    <input 
                        class="form-check-input" 
                        type="radio" 
                        name="order_by" 
                        id="flexRadioDefault1" 
                        value="default" 
                        {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault1">
                        По умолчанию
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input 
                        class="form-check-input" 
                        type="radio" 
                        name="order_by" 
                        id="flexRadioDefault2" 
                        value="price" 
                        {% if request.GET.order_by == 'price' %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault2">
                        От дешевых к дорогим
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input 
                        class="form-check-input" 
                        type="radio" 
                        name="order_by" 
                        id="flexRadioDefault3" 
                        value="-price" 
                        {% if request.GET.order_by == '-price' %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault3">
                        От дорогих к дешевым
                    </label>
                </div>
                <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
            </form>
        </div>

        {% if query %}
            <h1 class="mt-4" style="text-align: center;">По запросу "{{ query }}" ничего не найдено.</h1>
        {% if not tovari %}
            <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">            
        {% endif %}
        {% endif %}


        {% for product in tovari%}
        <!-- Карта товара -->
        <div class="col-lg-4 col-md-6 p-4">
            <div class="card border-primary rounded custom-shadow">
                {% if product.image %}
                    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                {% else %}
                    <img src="{% static "deps/images/Not found image.png" %}" class="card-img-top" alt="...">
                {% endif %}

                <div class="card-body">
                    <a href="{% url "catalog:product" product.slug %}">
                        <p class="card-title">
                            {% autoescape off %}
                                {% if product.headline %}
                                {{product.headline}}
                                {% else %}
                                {{product.name}}
                                {% endif %}
                            {% endautoescape %}
                        </p>
                    </a>
                    <p class="card-text">
                        {% autoescape off %}
                        {% if product.bodyline %}
                            {{ product.bodyline|safe }}
                        {% elif product.discription %}
                            {{ product.discription|truncatechars:35 }}
                        {% else %}
                            {{ product.name|truncatechars:35 }}
                        {% endif %}
                        {% endautoescape %}
                    </p>
                    
                    <p class="product_id">{{ product.display_id }}</p>
                    <div class="d-flex justify-content-between">
                        
                        {% if product.discount %}
                            <p><s>{{ product.price }}</s> $</p>
                            <p><strong><span style="background-color: yellow; color: rgb(255, 0, 30); padding: 5px; border-radius: 5px;">{{ product.sell_price }} $</span></strong></p>
                            <span class="badge bg-warning text-dark">Скидка {{ product.discount }}%</span>
                        {% else %}
                            <p><strong>{{ product.price }} $</strong></p>
                        {% endif %}

                        
                        <a href="{% url 'carts:cart_add' %}" class="btn add-to-cart"
                            data-product-id="{{ product.id }}">
                            {% csrf_token %}                            
                            <img class="mx-1" src="{% static 'deps/icons/cart-plus.svg' %}" alt="Catalog Icon" 
                            width="32" height="32">
                        </a>

                        
                    </div>
                </div>
            </div>
        </div>  
        {% endfor %}      
    </div>
     
    <!-- Пагинация -->
    {% if tovari %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center my-4">
            <div class="custom-shadow d-flex">
                <!-- Ссылка на предыдущую страницу -->
                <li class="page-item {% if not tovari.has_previous %}disabled{% endif %}">
                    <a class="page-link" href="?{% if tovari.has_previous %}{% change_params page=tovari.previous_page_number %}{% endif %}">Назад</a>
                </li>
    
                <!-- Номера страниц -->
                {% for page in tovari.paginator.page_range %}
                    {% if page >= tovari.number|add:"-1" and page <= tovari.number|add:"1" %}
                        <li class="page-item {% if tovari.number == page %}active{% endif %}">
                            <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                        </li>
                    {% endif %}
                    <!-- Троеточие и последняя страница -->
                    {% if page == tovari.number|add:"1" and page < tovari.paginator.num_pages %}
                        <li class="page-item disabled"><span class="page-link">...</span></li>
                        <li class="page-item">
                            <a class="page-link" href="?{% change_params page=tovari.paginator.num_pages %}">{{ tovari.paginator.num_pages }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
    
                <!-- Ссылка на следующую страницу -->
                <li class="page-item {% if not tovari.has_next %}disabled{% endif %}">
                    <a class="page-link" href="?{% if tovari.has_next %}{% change_params page=tovari.next_page_number %}{% endif %}">Вперед</a>
                </li>
            </div>
        </ul>
    </nav>
    {% endif %}
    
    
    
{% endblock %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Home Python Hub Studio 2023</p>
    </div>
</footer>
{% endblock %}

internet_shop/tovari/templates/tovari/product_pdf_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .product-image {
            width: 300px;
            height: auto;
        }
        .product-details {
            margin-top: 20px;
        }
        .product-title {
            font-size: 24px;
            font-weight: bold;
        }
        .product-price {
            font-size: 20px;
            color: green;
        }
        .product-description {
            margin-top: 20px;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="product-details">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image">

        <h1 class="product-title">{{ product.name }}</h1>

        <p class="product-price">Цена: {{ product.sell_price }} $</p>

        <p class="product-description">{{ product.description }}</p>
    </div>
</body>
</html>

internet_shop/tovari/templates/tovari/pusto.html
{% load static %}
{% load tovari_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'deps/css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block css %}

    {% endblock css %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'deps/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'deps/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'deps/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'deps/favicon/site.webmanifest' %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "shop:index" %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item text-white" href="{% url "shop:about" %}">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="carts/cart.html">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'users:login' %}">Войти</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-white" href="carts/included_cart.html">Корзина</a></li>
                                <li><a class="dropdown-item text-white" href="{% url 'users:profile' %}">Личный кабинет</a></li>
                                <li><a class="dropdown-item text-white" href="{% url 'admin:index' %}">Админ панель</a></li>

                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item text-white" href="{% url 'users:logout' %}">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search" action="{% url 'catalog:search' %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static 'deps/icons/grid-fill.svg' %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="{% url 'catalog:index' category.slug %}">{{category.name}}</a></li>
                        {% endfor %}                       
                  
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="{% static 'deps/icons/basket2-fill.svg' %}" alt="Catalog Icon" width="24"
                            height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Разметка модального окна корзины -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Товар</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 $</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="{% static 'deps/icons/trash3-fill.svg' %}"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                            <h4 class="float-left"><strong>100.00 $</strong></h4>
                                        </div>
                                    </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% block name %} {% endblock name %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %} {% endblock footer %}
    <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'deps/js/jquery-events.js' %}"></script>
    <script src="{% static 'deps/js/jquery-ajax.js' %}"></script>
    <script src="{% static 'deps/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>

</html> 