internet_shop/internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from internet_shop.settings import DEBUG
from django.conf.urls.static import static
from internet_shop import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('catalog/', include('tovari.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('orders/', include('orders.urls', namespace='orders')),
] 

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internet_shop/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order'),
]

internet_shop/shop/urls.py
from django.urls import path
from shop import views 

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'), 
    path('contacts/', views.contacts, name='contacts'),
]

internet_shop/users/urls.py
from django.urls import path
from users.views import LoginView, RegistrationView, ProfileView, LogoutView, UsersCartView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cart/', UsersCartView.as_view(), name='users_cart'),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

internet_shop/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser): 
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')

    class Meta:
        db_table = 'user' 
        verbose_name = 'Пользователя'     
        verbose_name_plural = 'Пользователь'

    def __str__(self):
        return self.username     

internet_shop/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User 
        fields = ['username', 'password']
        
    username = forms.CharField()
    password = forms.CharField()
    
class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )
first_name = forms.CharField()
last_name = forms.CharField()
username = forms.CharField()
email = forms.CharField()
password1 = forms.CharField()
password2 = forms.CharField()

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'image',
            'first_name',
            'last_name',
            'username',
            'email',
            )
        image = forms.ImageField()
        first_name = forms.CharField()
        last_name = forms.CharField()
        username = forms.CharField()
        email = forms.CharField()

internet_shop/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, TemplateView, FormView
from carts.models import Cart
from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm


class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def form_valid(self, form):
        username = self.request.POST['username']
        password = self.request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            auth_login(self.request, user)
            messages.success(self.request, 'Вы вошли в аккаунт.')

            redirect_page = self.request.POST.get('next', None)
            if redirect_page and redirect_page != reverse('user:logout'):
                return HttpResponseRedirect(redirect_page)

            return HttpResponseRedirect(reverse('shop:index'))
        else:
            messages.error(self.request, 'Неправильное имя пользователя или пароль.')
        return super().form_invalid(form)


class RegistrationView(FormView):
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm

    def form_valid(self, form):
        user = form.save()
        messages.success(self.request, 'Вы успешно зарегистрировались! Добро пожаловать в систему.')
        auth_login(self.request, user)
        return redirect('shop:index')

    def form_invalid(self, form):
        messages.error(self.request, 'Пожалуйста, исправьте ошибки в форме.')
        return super().form_invalid(form)


class ProfileView(LoginRequiredMixin, FormView):
    template_name = 'users/profile.html'
    form_class = ProfileForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.request.user  
        return kwargs

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        messages.success(self.request, 'Ваш профиль был успешно обновлен.')
        return redirect('users:profile')

    def form_invalid(self, form):
        messages.error(self.request, 'Пожалуйста, исправьте ошибки в форме.')
        return super().form_invalid(form)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        messages.success(request, f'{request.user.username}, Вы вышли из аккаунта')
        auth_logout(request)
        return redirect(reverse('shop:index'))


class UsersCartView(LoginRequiredMixin, TemplateView):
    template_name = 'users/users_cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_items = Cart.objects.filter(user=self.request.user)
        context['cart_items'] = cart_items
        context['total_price'] = sum(item.product_price() for item in cart_items)
        context['total_quantity'] = sum(item.quantity for item in cart_items)
        return context

internet_shop/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Авторизация</h2>
                
                
                <form action="{% url 'users:login' %}" method="post">
                    {% csrf_token %}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{request.GET.next}}">
                    {% endif %}

                    <div class="mb-3">
                        <label for="id_username" class="form-label">Имя пользователя</label>
                        <input type="text" class="form-control" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" id="username" name="username" placeholder="Введите ваше имя пользователя" required>
                    </div>
                    
                    <div class="mb-3 position-relative">
                        <label for="id_password" class="form-label">Пароль</label>
                        <div class="position-relative">
                            <input type="password" class="form-control" id="password" name="password" placeholder="Введите ваш пароль" required>
                            
                            <button type="button" class="btn toggle-password-btn" id="toggle-password" style="position: absolute; top: 50%; right: 10px; transform: translateY(-50%); visibility: hidden; background: transparent; border: none;">
                                <i class="fas fa-eye" id="password-icon"></i>
                            </button>
                        </div>
                    </div>
                
                    <button type="submit" class="btn btn-dark btn-block">Войти</button>
                </form>
                
                
                
                <script>
                    document.addEventListener("DOMContentLoaded", function () {
                        const passwordInput = document.getElementById("password");
                        const togglePasswordButton = document.getElementById("toggle-password");
                        const passwordIcon = document.getElementById("password-icon");
                
                        passwordInput.addEventListener("input", function () {
                            if (passwordInput.value) {
                                togglePasswordButton.style.visibility = "visible";
                            } else {
                                togglePasswordButton.style.visibility = "hidden"; 
                            }
                        });
                
                        togglePasswordButton.addEventListener("click", function () {
                            const type = passwordInput.type === "password" ? "text" : "password";
                            passwordInput.type = type;
                
                            passwordIcon.classList.toggle("fa-eye");
                            passwordIcon.classList.toggle("fa-eye-slash");
                        });
                    });
                </script>
                
                


                <div class="mt-3">
                    <a href="#">Забыли пароль?</a> | <a href="{% url 'users:registration' %}">Создать аккаунт</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Или авторизуйтесь через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/google.svg' %}" alt="Google Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/facebook.svg' %}" alt="Facebook Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/github.svg' %}" alt="GitHub Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

internet_shop/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}


{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-5">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Профиль пользователя</h3>
                        <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 mb-3 text-center">
                                    <img src="{% if user.image %}{{ user.image.url }}{% else %}{% static 'deps/images/baseavatar.jpg' %}{% endif %}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle" style="max-width: 150px;">
                                    <input type="file" class="form-control mt-3" id="id_image" name="image" accept="image/*">
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_first_name" class="form-label">Имя*</label>
                                    <input type="text" class="form-control" id="id_first_name" name="first_name"
                                           placeholder="Введите ваше имя" value="{{ form.first_name.value }}" required>
                                    {% if form.first_name.errors %}
                                        <div class="alert alert-danger mt-1">{{ form.first_name.errors|join:", " }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_last_name" class="form-label">Фамилия*</label>
                                    <input type="text" class="form-control" id="id_last_name" name="last_name"
                                           placeholder="Введите вашу фамилию" value="{{ form.last_name.value }}" required>
                                    {% if form.last_name.errors %}
                                        <div class="alert alert-danger mt-1">{{ form.last_name.errors|join:", " }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_username" class="form-label">Имя пользователя*</label>
                                    <input type="text" class="form-control" id="id_username" name="username"
                                           placeholder="Введите имя пользователя" value="{{ form.username.value }}" required>
                                    {% if form.username.errors %}
                                        <div class="alert alert-danger mt-1">{{ form.username.errors|join:", " }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_email" class="form-label">Email*</label>
                                    <input type="email" class="form-control" id="id_email" name="email"
                                           placeholder="Введите ваш email" value="{{ form.email.value }}" required>
                                    {% if form.email.errors %}
                                        <div class="alert alert-danger mt-1">{{ form.email.errors|join:", " }}</div>
                                    {% endif %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-dark">Сохранить</button>
                        </form>
                        
                    </div>
                </div>
                
                {% user_carts request as carts %}
                
                <div class="col-md-7">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Корзина</h3>
                        <div class="container" id="cart-items-container">
                            {% include 'carts/includes/included_cart.html' %}
                        </div>

                        {% if carts %}
                            <a class="btn btn-dark" href="{% url 'orders:create_order' %}">
                                Оформить заказ
                            </a>
                        {% endif %}

                <div class="col-md-12">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Мои заказы</h3>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

internet_shop/users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                
                {% if form.errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <ul>
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                <li>{{ field|capfirst }}: {{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}

                <form action="{% url 'users:registration' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя*</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{{ form.first_name.value|default_if_none:'' }}"
                                name="first_name"
                                placeholder="Введите ваше имя" required>
                            {% if form.first_name.errors %}
                                <div class="alert alert-danger mt-1">{{ form.first_name.errors|join:', ' }}</div>
                            {% endif %}
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия*</label>
                            <input type="text" class="form-control" id="id_last_name"
                                value="{{ form.last_name.value|default_if_none:'' }}"
                                name="last_name"
                                placeholder="Введите вашу фамилию" required>
                            {% if form.last_name.errors %}
                                <div class="alert alert-danger mt-1">{{ form.last_name.errors|join:', ' }}</div>
                            {% endif %}
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username"
                                value="{{ form.username.value|default_if_none:'' }}"
                                name="username"
                                placeholder="Введите имя пользователя" required>
                            {% if form.username.errors %}
                                <div class="alert alert-danger mt-1">{{ form.username.errors|join:', ' }}</div>
                            {% endif %}
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                                value="{{ form.email.value|default_if_none:'' }}"
                                name="email"
                                placeholder="Введите ваш Email" required>
                            {% if form.email.errors %}
                                <div class="alert alert-danger mt-1">{{ form.email.errors|join:', ' }}</div>
                            {% endif %}
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1"
                                name="password1"
                                placeholder="Введите пароль" required>
                            {% if form.password1.errors %}
                                <div class="alert alert-danger mt-1">{{ form.password1.errors|join:', ' }}</div>
                            {% endif %}
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2"
                                name="password2"
                                placeholder="Подтвердите пароль" required>
                            {% if form.password2.errors %}
                                <div class="alert alert-danger mt-1">{{ form.password2.errors|join:', ' }}</div>
                            {% endif %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

internet_shop/users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}

{% load carts_tags %}

{% block content %} 
{% user_carts request as carts %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include "carts/includes/included_cart.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
                {% if carts %}
                <a class="btn btn-dark" href="{% url 'orders:create_order' %}">
                    Оформить заказ
                </a>
                {% endif %}
                
            </div>
        </div>
    </div>
</div>    
{% endblock %}