internet_shop/internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from internet_shop.settings import DEBUG
from django.conf.urls.static import static
from internet_shop import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('catalog/', include('tovari.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('orders/', include('orders.urls', namespace='orders')),
] 

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internet_shop/shop/urls.py
from django.urls import path
from shop import views 

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'), 
    path('contacts/', views.contacts, name='contacts'),
]

internet_shop/tovari/urls.py
from django.urls import path
from tovari.views import (
    ProductListAPIView, 
    ProductDetailAPIView, 
    generate_pdf, 
    catalog, 
    product
)

app_name = 'tovari'

urlpatterns = [
    # API маршруты
    path('api/products/', ProductListAPIView.as_view(), name='product_list'),
    path('api/products/<int:pk>/', ProductDetailAPIView.as_view(), name='product_detail'),

    # Маршруты каталога и товаров
    path('catalog/<slug:category_slug>/', catalog, name='catalog'),
    path('product/<slug:product_slug>/', product, name='product'),

    # Маршрут для генерации PDF
    path('generate-pdf/<slug:product_slug>/', generate_pdf, name='generate_pdf'),

    # Поиск (если используется)
    path('search/', catalog, name='search'),
    path('<slug:category_slug>/', catalog, name='index'),
]

internet_shop/users/urls.py
from django.urls import path
from users.views import LoginView, RegistrationView, ProfileView, LogoutView, UsersCartView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cart/', UsersCartView.as_view(), name='users_cart'),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

internet_shop/templates/base.html
{% load static %}
{% load tovari_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'deps/css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
    {% block css %}

    {% endblock css %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'deps/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'deps/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'deps/favicon/favicon-16x16.png' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link rel="manifest" href="{% static 'deps/favicon/site.webmanifest' %}">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>{{ title }}</title>
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "shop:index" %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-white" href="{% url "shop:contacts" %}">Контактная информация</a></li>
                                <li><a class="dropdown-item text-white" href="{% url "shop:about" %}">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'users:users_cart' %}">Корзина</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-white" href="{% url 'users:users_cart' %}">Корзина</a></li>
                                <li><a class="dropdown-item text-white" href="{% url 'users:profile' %}">Личный кабинет</a></li>
                                {% if user.is_admin or user.is_staff %}
                                    <li><a class="dropdown-item text-white" href="{% url 'admin:index' %}">Админ панель</a></li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item text-white" href="{% url 'users:logout' %}">Выйти</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'users:login' %}">Войти</a>
                        </li>
                    {% endif %}
                        
                        
                    </ul>
                    <form class="d-flex" role="search" action="{% url 'catalog:search' %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static 'deps/icons/grid-fill.svg' %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="{% url 'catalog:index' category.slug %}">{{category.name}}</a></li>
                        {% endfor %}                       
                  
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                {% block modal_cart %}{% endblock %}
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% include "includes/notifications.html" %}

                    {% block content %}
                        {% block name %}{% endblock name %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %} {% endblock footer %}
    <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script>
        window.$j = jQuery.noConflict();
        $j(document).ready(function () {
            console.log("jQuery работает без конфликта!");
            $j('body').css('background-color', 'lightblue');
        });
    </script>
    <script src="{% static 'deps/js/jquery-ajax.js' %}"></script>
    <script src="{% static 'deps/js/bootstrap/bootstrap.bundle.min.js' %}"></script>

        
</body>

</html> 