internet_shop/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
    path('cart_change/', views.cart_change, name='cart_change'),
]

internet_shop/internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from internet_shop.settings import DEBUG
from django.conf.urls.static import static
from internet_shop import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('catalog/', include('tovari.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('orders/', include('orders.urls', namespace='orders')),
] 

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internet_shop/shop/urls.py
from django.urls import path
from shop import views 

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'), 
    path('contacts/', views.contacts, name='contacts'),
]

internet_shop/carts/models.py
from django.db import models
from tovari.models import Products
from users.models import User


class CartQueryset(models.QuerySet):
    def total_price(self):
        return sum(cart.product_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Cart(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    session_key = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        db_table = 'cart'
        verbose_name: str = "Корзина"
        verbose_name_plural: str = "Корзина"

    objects = CartQueryset().as_manager()

    def product_price(self):
        return round(self.product.sell_price()* self.quantity, 2)   

    def __str__(self) -> str:
        return f'Корзина {self.user.username} | Товар {self.product.name} | Количество {self.quantity}'

internet_shop/carts/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from carts.utils import get_user_carts
from .models import Cart

from tovari.models import Products
from django.template.loader import render_to_string

def cart_add(request):

    product_id = request.POST.get("product_id")

    product = Products.objects.get(id=product_id)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)
            
    user_cart = get_user_carts(request)

    cart_items_html = render_to_string(
        "carts/includes/incleded_cart.html", {"carts": user_cart}, request=request
    )

    response_data = {
        "message": "Товар добавлен в корзину",
        "cart_items_html": cart_items_html,
    }

    return JsonResponse(response_data)


def cart_add(request):

    product_id = request.POST.get("product_id")

    product = get_object_or_404(Products, id=product_id)

    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(
            user=request.user, product=product
        )
        if not created:
            cart.quantity += 1
            cart.save()

    user_cart = get_user_carts(request)

    total_quantity = sum(item.quantity for item in user_cart)

    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart}, request=request
    )

    response_data = {
        "message": "Товар успешно добавлен в корзину",
        "cart_items_html": cart_items_html,
        "total_quantity": total_quantity,
    }

    return JsonResponse(response_data)






def cart_change(request) -> JsonResponse:
    cart_id = request.POST.get("cart_id")
    quantity = request.POST.get("quantity")

    cart = Cart.objects.get(id=cart_id)

    cart.quantity = quantity
    cart.save()
    updated_quantity = cart.quantity

    cart_items = get_user_carts(request).order_by('id')  

    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": cart_items}, request=request
    )

    response_data = {
        "message": "Количество изменено",
        "cart_items_html": cart_items_html,
        "quantity": updated_quantity,
    }

    return JsonResponse(response_data)




def cart_remove(request):
    cart_id = request.POST.get('cart_id')
    cart = get_object_or_404(Cart, id=cart_id)

    cart.delete()

    user_cart = get_user_carts(request)

    total_quantity = sum(item.quantity for item in user_cart)
    total_price = sum(item.quantity * item.product.sell_price() for item in user_cart)

    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart}, request=request
    )

    response_data = {
        "message": "Товар удален из корзины",
        "cart_items_html": cart_items_html,
        "total_quantity": total_quantity,  
        "total_price": total_price,        
    }

    return JsonResponse(response_data)

internet_shop/carts/templates/carts/includes/included_cart.html
{% load static %}

<div>
    <!-- Кнопка для открытия модального окна -->
    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
        data-bs-toggle="modal" data-bs-target="#exampleModal" aria-expanded="false">
        <img class="mx-1" src="{% static 'deps/icons/basket2-fill.svg' %}" alt="Basket Icon" width="24" height="24">
        <!-- Здесь обновляется количество товаров -->
        <span id="tovar-in-cart-count">{{ carts.total_quantity }}</span>
    </button>
</div>

<div class="card mb-3 text-bg-light shadow-lg">
    <!-- Здесь обновляется содержимое корзины -->
    <div id="cart-items-container">
        {% for cart in carts %}
        <div class="card-header">
            <h5 class="card-title">{{ cart.product.name }}</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row text-center">
                    <div class="col p-0">
                        <div class="input-group">



                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm decrement"
                                    data-cart-id="{{ cart.id }}" 
                                    data-cart-change-url="{% url 'carts:cart_change' %}">
                                    {% csrf_token %}-</button>
                            </span>
                            <input type="text" class="form-control number" value="{{ cart.quantity }}" readonly>
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm increment"
                                    data-cart-id="{{ cart.id }}" 
                                    data-cart-change-url="{% url 'carts:cart_change' %}">+</button>
                            </span>




                        </div>
                    </div>
                    <div class="col p-0">
                        <p>x {{ cart.product.sell_price }} = </p>
                    </div>
                    <div class="col p-0"><strong>{{ cart.product_price }}$</strong></div>
                    <div class="col p-0">
                        
                        <a href="{% url 'carts:cart_remove' %}" 
                            class="remove-from-cart" 
                            data-cart-id="{{ cart.id }}">
                            <img src="{% static 'deps/icons/trash3-fill.svg' %}" alt="Удалить" width="16" height="16">
                        </a>


                    </div>
                </div>
            </li>
        </ul>
        {% endfor %}
    </div>
</div>

<div class="card mb-3 shadow-lg">
    <!-- Здесь обновляется итоговая сумма -->
    <div class="card-footer">
        <p class="float-left">Итого <strong id="total-items-count">{{ carts.total_quantity }}</strong> товар(а) на сумму</p>
        <h4 class="float-left"><strong id="total-price">{{ carts.total_price }} $</strong></h4>
    </div>
</div>